const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const M=require('../canonical-metrics.js');
const acct=(nav=100)=>({nav,positions:[],cash_krw:0,cash_usd:0,today_pnl:1,today_return:1,net_flow:0,principal:90});
const live=()=>({schema:'JJOONI_CT_LIVE_V5',snapshot_id:'fixture',generated_kst:'2026-09-07T21:03:00+09:00',observed_at:'2026-09-07T21:03:00+09:00',accounts:Object.fromEntries(M.IDS.map(id=>[id,acct()]))});
function bridge(){const c={window:{JjooniMetrics:M},D:{human:{positions:[],performance:[]},ai:{}},console,Intl,Date,Number,TextEncoder,TextDecoder};vm.createContext(c);let s=fs.readFileSync(path.join(__dirname,'../live-bridge.js'),'utf8');s=s.slice(0,s.indexOf('injectResponsiveCss();ensureWatchlistUi();refresh();'));vm.runInContext(s+'window.test={makeCanonical,mergePositions,syncLegacyMirrors,applyLive,setCanon:x=>CANON=x,setLast:x=>LAST_LIVE=x};})();',c);return c}
function router(C){const c={window:{JjooniMetrics:M,__JJOONI_CANONICAL_SSOT:C},document:{querySelector:()=>null,querySelectorAll:()=>[]},Intl,Number,console};vm.createContext(c);let s=fs.readFileSync(path.join(__dirname,'../metric-drilldown-router-v12.js'),'utf8');s=s.slice(0,s.indexOf("document.addEventListener('click',capture,true)"));vm.runInContext(s+'window.test={rowsAccount,mainRows,snap,contrib,contributionItems};})();',c);return c.window.test}
test('missing is distinct from zero throughout numeric inputs',()=>{for(const x of [null,undefined,'', ' ',false,{},NaN,Infinity])assert.equal(M.number(x),null);assert.equal(M.number(0),0);assert.equal(M.sum([1,null]),null)});
test('KRW canonical values are not converted twice and FX is account specific',()=>{const p={currency:'USD',market_value:13000};assert.equal(M.valueKrw(p,{fx:1500}),13000);assert.equal(M.valueKrw({currency:'USD',value:10},{fx:1400}),14000);assert.equal(M.valueKrw({currency:'USD',value:10},{}),null)});
test('cash includes USD with the same account FX and preserves confirmed zero',()=>{assert.equal(M.cash({cash_krw:300,cash_usd:2,fx_krw_per_usd:1400}),3100);assert.equal(M.cash({cash_krw:0,cash_usd:0}),0);assert.equal(M.cash({cash_krw:0,cash_usd:2}),null);assert.equal(M.cash({cash_krw:3,cash_usd:2,fx:1400,cash_krw_equiv:2900}),2900)});
test('funds are included once; cash and watchlists are excluded',()=>{assert.equal(M.stock({positions:[{record_type:'POSITION',market_value:100},{record_type:'FUND',market_value:40},{record_type:'CASH',market_value:20},{record_type:'WATCHLIST',market_value:800}]}),140)});
test('aggregate returns use previous NAV and never assume missing flows are zero',()=>{const a={A:{nav:120,today_pnl:10,net_flow:10}};assert.equal(M.aggregate(a,['A']).day_return,10);a.A.net_flow=null;assert.equal(M.aggregate(a,['A']).day_return,null)});
test('freshness follows the scheduled deadline through market close',()=>{const p={generated_kst:'2026-09-07T16:00:00+09:00',stale_after_kst:'2026-09-08T09:08:00+09:00',market_closed:true};assert.equal(M.freshness(p,Date.parse('2026-09-08T08:00:00+09:00')).state,'CLOSED');assert.equal(M.freshness(p,Date.parse('2026-09-08T09:09:00+09:00')).state,'STALE');assert.equal(M.freshness(p,Date.parse('2026-09-07T15:00:00+09:00')).state,'UNKNOWN')});
test('source date is KST and accepts compact historical dates',()=>{assert.equal(M.dayKey('20260907'),'2026-09-07');assert.equal(M.dayKey('2026-09-07T16:00:00Z'),'2026-09-08')});
test('latest empty holdings remove sold positions and old fund rows',()=>{const c=bridge(),p=live();c.D.human.positions=[{account:'TOSS',ticker:'OLD'},{account:'IRP',record_type:'FUND',ticker:'F1'}];p.accounts.IRP.positions=[{record_type:'FUND',ticker:'F1',market_value:40}];c.window.test.mergePositions(p);assert.equal(c.D.human.positions.filter(x=>x.account==='TOSS').length,0);assert.equal(c.D.human.positions.filter(x=>x.ticker==='F1').length,1)});
test('legacy Human totals contain four accounts and update the observation date once',()=>{const c=bridge(),p=live();c.D.human.performance=[{date:'20260907',account:'TOTAL',total_asset:999}];const C=c.window.test.makeCanonical(p);c.window.test.setCanon(C);c.window.test.syncLegacyMirrors();c.window.test.syncLegacyMirrors();assert.equal(C.total.nav,600);assert.equal(c.D.human.total_asset,400);assert.equal(c.D.human.performance.filter(x=>x.account==='TOTAL').length,1);assert.equal(c.D.human.performance[0].date,'2026-09-07');assert.equal(c.D.human.performance[0].total_asset,400)});
test('old snapshots and invalid timestamps are rejected before mutating data',()=>{const c=bridge(),p=live();c.window.test.setLast(p);const old={...p,generated_kst:'2026-09-06T12:00:00+09:00'};assert.throws(()=>c.window.test.applyLive(old),/SNAPSHOT_ROLLBACK/);assert.equal(c.window.__JJOONI_LIVE_PAYLOAD,undefined);assert.throws(()=>c.window.test.applyLive({...p,generated_kst:'invalid'}),/INVALID_SNAPSHOT_TIME/)});
test('cumulative principal and net flow are not copied from stale static history',()=>{const c=bridge(),p=live();delete p.accounts.ISA.principal;delete p.accounts.ISA.net_flow;c.D.human.performance=[{account:'ISA',principal:50,net_cash_flow:0}];const C=c.window.test.makeCanonical(p);assert.equal(C.accounts.ISA.principal,null);assert.equal(C.accounts.ISA.pnl,null);assert.equal(C.accounts.ISA.net_flow,null);assert.equal(C.total.pnl,null)});
test('cash drilldown headline basis and detail total reconcile; fund detail is exhaustive',()=>{const c=bridge(),p=live();p.accounts.TOSS={...acct(),cash_krw:300,cash_usd:2,fx:1400,positions:Array.from({length:14},(_,i)=>({ticker:String(i),record_type:i===13?'FUND':'POSITION',market_value:10}))};const r=router(c.window.test.makeCanonical(p));assert.equal(r.snap('TOSS').cash,3100);assert.equal(r.rowsAccount('TOSS','예수금').find(x=>x[0]==='합산 현금')[1],'₩3,100');assert.equal(r.rowsAccount('TOSS','주식 평가액').length,17)});
test('price contributions disclose remainder and unexplained account residual; Best/Worst work',()=>{const c=bridge(),p=live();p.accounts.TOSS={...acct(),today_pnl:100,positions:Array.from({length:12},(_,i)=>({ticker:String(i),qty:1,daily_pnl:i+1,market_value:10}))};const r=router(c.window.test.makeCanonical(p)),rows=r.rowsAccount('TOSS','당일 투자성과');assert.equal(rows.find(x=>x[0].startsWith('나머지'))[1],'+₩3');assert.equal(rows.find(x=>x[0].startsWith('계좌손익과 차이'))[1],'+₩22');assert.equal(r.rowsAccount('TOSS','Best')[0][1],'11');assert.equal(r.rowsAccount('TOSS','Worst')[0][1],'0')});

function completeness(C){const c={window:{JjooniMetrics:M,__JJOONI_CANONICAL_SSOT:C},document:{},Intl,Number,console};vm.createContext(c);let s=fs.readFileSync(path.join(__dirname,'../position-completeness-v25.js'),'utf8');s=s.slice(0,s.indexOf('apply();[100,350'));vm.runInContext(s+'window.test={posMetrics,fillBox,accountIdFromModal};})();',c);return c.window.test}
test('v25 keeps Toss USD daily_pnl in its declared KRW unit',()=>{const C={accounts:{TOSS:{fx_krw_per_usd:1400}}},r=completeness(C);const x=r.posMetrics('TOSS',{currency:'USD',qty:2,avg_price:10,current_price:11,market_value:30800,daily_pnl:2800,daily_return:10});assert.equal(x.day_pnl,2800);assert.equal(x.value,30800);assert.equal(x.cum_pnl,2800);assert.equal(x.day_return,10)});
test('v25 own DOM writes are idempotent and cannot trigger an endless observer loop',()=>{const r=completeness({accounts:{}});let html='',writes=0;const box={get innerHTML(){return html},set innerHTML(v){html=v;writes++}};r.fillBox(box,'TOSS',[],'fixture');r.fillBox(box,'TOSS',[],'fixture');assert.equal(writes,1)});
test('v25 funds disclose absent day basis while keeping cumulative fields',()=>{const r=completeness({accounts:{IRP:{}}});const x=r.posMetrics('IRP',{record_type:'FUND',qty:1,market_value:110,avg_price:100,current_price:110});assert.equal(x.day_na,true);assert.equal(x.cum_pnl,10);assert.equal(x.day_reason,'FUND_DAILY_BASIS_NOT_AVAILABLE')});
function loader({runtime={},existing=null,onAppend=()=>{},timer}={}){const window={...runtime},document={head:{appendChild:s=>onAppend(s,window)},documentElement:{},getElementById:()=>existing,createElement:()=>({dataset:{},addEventListener(){}})};const c={window,document,Date,Promise,setTimeout:timer||setTimeout,clearTimeout,console};vm.createContext(c);let s=fs.readFileSync(path.join(__dirname,'../trade-review-loader.js'),'utf8');s=s.slice(0,s.lastIndexOf('boot();'));vm.runInContext(s+'window.test={loadRequired,runtimeReady};})();',c);return window}
test('loader accepts an already executed module without waiting for a past load event',async()=>{let append=0;const w=loader({runtime:{__JJOONI_MARKET_CONTEXT_V20:{state:'ACTIVE'}},existing:{dataset:{},addEventListener(){}},onAppend:()=>append++});await w.test.loadRequired('market','m.js','market-context');assert.equal(append,0)});
test('loader rejects a loaded file whose required runtime failed to initialize',async()=>{const w=loader({onAppend:s=>s.onload()});await assert.rejects(w.test.loadRequired('detail','detail.js','position-completeness'),/RUNTIME_NOT_READY/)});
test('loader bounds an unresolved existing script with a useful module error',async()=>{const w=loader({existing:{dataset:{},addEventListener(){}},timer:fn=>setTimeout(fn,1)});await assert.rejects(w.test.loadRequired('missing','m.js','position-completeness'),/LOAD_TIMEOUT/)});
