(()=>{
'use strict';
const RAW={};
const RANGE_ORDER=['1M','3M','6M','1Y','3Y','5Y','10Y','20Y','30Y','ALL'];
const DAYS={'1M':31,'3M':92,'6M':184,'1Y':366,'3Y':1096,'5Y':1827,'10Y':3653,'20Y':7306,'30Y':10958,'ALL':999999};
const active={};let fullChart=null;

// V2.4 contract: the base page previously truncated every merged series to the
// latest 260 observations (~1 year). Override that global helper so the range
// controls receive the complete hydrated history. Filtering now happens only
// at chart render time.
function fullCommon(keys){
 const map=new Map();
 if(typeof DATA==='undefined'||!DATA?.series)return[];
 for(const k of keys)for(const p of(DATA.series[k]||[])){
   if(!p?.date)continue;
   if(!map.has(p.date))map.set(p.date,{date:p.date});
   map.get(p.date)[k]=p.value;
 }
 return [...map.values()].sort((a,b)=>String(a.date).localeCompare(String(b.date)));
}
try{globalThis.common=fullCommon}catch(_){}

function cutoffFor(labels,range){if(range==='ALL'||!labels?.length)return null;const last=String(labels[labels.length-1]);const d=new Date(last+'T00:00:00Z');if(Number.isNaN(d.getTime()))return null;d.setUTCDate(d.getUTCDate()-DAYS[range]);return d.toISOString().slice(0,10)}
function filtered(labels,sets,range){const cut=cutoffFor(labels,range);if(!cut)return{labels,sets};let i=labels.findIndex(x=>String(x)>=cut);if(i<0)i=0;return{labels:labels.slice(i),sets:sets.map(s=>({...s,data:(s.data||[]).slice(i)}))}}
function chartConfig(labels,sets){return{type:'line',data:{labels,datasets:sets.map(x=>({label:x.label,data:x.data,borderWidth:2,pointRadius:0,tension:.12,spanGaps:true}))},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},animation:false,plugins:{legend:{display:true,position:'bottom',labels:{boxWidth:12,font:{size:10}}},zoom:{limits:{x:{min:'original',max:'original'}},pan:{enabled:true,mode:'x'},zoom:{wheel:{enabled:true,speed:.08},pinch:{enabled:true},mode:'x'}}},scales:{x:{ticks:{maxTicksLimit:8,maxRotation:0,font:{size:9}}},y:{ticks:{maxTicksLimit:6,font:{size:9}}}}}}}
function ensureFullscreen(){let o=document.getElementById('obsFullChart');if(o)return o;o=document.createElement('div');o.id='obsFullChart';o.innerHTML='<div class="obsFullHead"><b id="obsFullTitle">차트 크게 보기</b><button id="obsFullReset">줌 초기화</button><button id="obsFullClose">닫기 ✕</button></div><div class="obsFullBody"><canvas id="obsFullCanvas"></canvas></div><div class="obsFullHint">두 손가락 확대/축소 · 좌우 드래그 이동 · 기기를 가로로 돌리면 더 넓게 볼 수 있습니다.</div>';document.body.appendChild(o);o.querySelector('#obsFullClose').onclick=closeFullscreen;o.querySelector('#obsFullReset').onclick=()=>{try{fullChart?.resetZoom()}catch(_){}};o.addEventListener('click',e=>{if(e.target===o)closeFullscreen()});return o}
function openFullscreen(id){const r=RAW[id];if(!r)return;const o=ensureFullscreen(),range=active[id]||'5Y',f=filtered(r.labels,r.sets,range);o.classList.add('on');document.body.classList.add('obsNoScroll');const title=document.querySelector(`#${id}`)?.closest('.card')?.querySelector('h3')?.textContent||id;o.querySelector('#obsFullTitle').textContent=title+' · '+range;if(fullChart)fullChart.destroy();fullChart=new Chart(o.querySelector('#obsFullCanvas'),chartConfig(f.labels,f.sets))}
function closeFullscreen(){const o=document.getElementById('obsFullChart');if(o)o.classList.remove('on');document.body.classList.remove('obsNoScroll');if(fullChart){fullChart.destroy();fullChart=null}}
function coverageText(id){const r=RAW[id];if(!r?.labels?.length)return'';const first=r.labels[0],last=r.labels[r.labels.length-1];return `${first} → ${last} · ${r.labels.length.toLocaleString()}pt`}
function ensureToolbar(id){const canvas=document.getElementById(id);if(!canvas||canvas.dataset.rangeReady)return;canvas.dataset.rangeReady='1';const wrap=canvas.parentElement,bar=document.createElement('div');bar.className='range obsRange';bar.dataset.for=id;for(const r of RANGE_ORDER){const b=document.createElement('button');b.textContent=r;b.dataset.range=r;b.classList.toggle('on',(active[id]||'5Y')===r);b.onclick=()=>{active[id]=r;bar.querySelectorAll('button[data-range]').forEach(x=>x.classList.toggle('on',x===b));redraw(id)};bar.appendChild(b)}const reset=document.createElement('button');reset.textContent='줌 초기화';reset.onclick=()=>{try{charts[id]?.resetZoom()}catch(_){}};bar.appendChild(reset);const full=document.createElement('button');full.textContent='⛶ 크게 보기';full.className='obsFullBtn';full.onclick=()=>openFullscreen(id);bar.appendChild(full);const note=document.createElement('span');note.className='meta obsGesture';note.textContent='휠/핀치 확대 · 드래그 이동';bar.appendChild(note);const cov=document.createElement('span');cov.className='obsCoverage';cov.dataset.coverage=id;cov.textContent=coverageText(id);bar.insertAdjacentElement('afterend',cov);wrap.insertBefore(bar,canvas)}
function refreshCoverage(id){const el=document.querySelector(`[data-coverage="${id}"]`);if(el)el.textContent=coverageText(id)}
function draw(id,labels,sets){if(charts[id])charts[id].destroy();const c=document.getElementById(id);if(!c)return;const f=filtered(labels,sets,active[id]||'5Y');charts[id]=new Chart(c,chartConfig(f.labels,f.sets));ensureToolbar(id);refreshCoverage(id)}
function redraw(id){const r=RAW[id];if(r)draw(id,r.labels,r.sets)}
window.chart=function(id,labels,sets){RAW[id]={labels:[...(labels||[])],sets:(sets||[]).map(s=>({...s,data:[...(s.data||[])]}))};draw(id,labels,sets)};
function val(v){return v==null||v===''?'—':String(v)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]))}
function eventMetricsHtml(e){
 const ms=(e.market_metrics||[]).filter(m=>m&&m.label);
 if(ms.length){
   return `<div class="obsMetricTable">${ms.map(m=>`<div class="obsMetricRow"><div class="obsMetricName">${esc(m.label)}</div><div class="obsPrev">이전 <b>${esc(val(m.previous))}</b></div><div class="forecast">예측 <b>${esc(val(m.consensus))}</b></div><div class="actual">실제 <b>${esc(val(m.actual))}</b></div></div>`).join('')}</div>`;
 }
 return `<div class="obsEventMetrics"><span>이전 <b>${esc(val(e.previous))}</b></span><span>예측 <b>${esc(val(e.consensus))}</b></span><span>실제 <b>${esc(val(e.actual))}</b></span></div>`;
}
window.renderCalendar=function(){if(typeof CAL==='undefined')return;const month=typeof calMonth!=='undefined'?calMonth:new Date().toISOString().slice(0,7);const title=document.querySelector('#calendarMonth');if(title)title.textContent=month;const xs=(CAL.events||[]).filter(e=>String(e.datetime_kst||e.date||'').startsWith(month));const box=document.querySelector('#events');if(!box)return;box.innerHTML=xs.length?xs.map(e=>{const dt=(e.datetime_kst||e.date||'').slice(5,16).replace('T',' '),hasActual=(e.market_metrics||[]).some(m=>m?.actual!=null)||e.actual!=null,status=hasActual?'<span class="obsDone">발표완료</span>':'<span class="obsPending">예정</span>';return `<div class="event"><div class="date">${esc(dt)}</div><div class="country">${esc(e.country)}</div><div class="obsEventMain"><div class="event-title">${esc(e.title)}</div><div class="event-meta">${esc(e.category||'')}${e.reference_period?' · '+esc(e.reference_period):''} · ${status}</div>${eventMetricsHtml(e)}</div><div class="importance">${'★'.repeat(e.importance||1)}<div class="source">${esc(e.source||'')}${e.market_data_source?' · '+esc(e.market_data_source):''}</div></div></div>`}).join(''):'<div class="meta" style="padding:20px 0">등록된 일정이 없습니다.</div>'};
function mergeSeries(base,recent){const m=new Map();for(const x of(base||[]))if(x?.date)m.set(x.date,x);for(const x of(recent||[]))if(x?.date)m.set(x.date,x);return[...m.values()].sort((a,b)=>String(a.date).localeCompare(String(b.date)))}
async function hydrateHistory(){try{const h=await fetch('./data/history-30y.json',{cache:'force-cache'}).then(r=>r.ok?r.json():Promise.reject(new Error('history '+r.status)));if(typeof DATA==='undefined'||!DATA)return;const merged={},hs=h.series||{},rs=DATA.series||{};for(const k of new Set([...Object.keys(hs),...Object.keys(rs)]))merged[k]=mergeSeries(hs[k],rs[k]);DATA.series=merged;DATA.history_loaded=true;DATA.history_base_generated_kst=h.generated_kst||null;try{globalThis.common=fullCommon}catch(_){};if(typeof render==='function')render();Object.keys(RAW).forEach(refreshCoverage)}catch(e){console.warn('30Y history cache unavailable',e)}}
const style=document.createElement('style');style.textContent=`
html,body{max-width:100%;overflow-x:hidden}.wrap,.panel,.grid,.card,.chart,.events,.event,.obsEventMain{min-width:0}.card{overflow:hidden}.chart{width:100%;max-width:100%}.chart canvas{max-width:100%!important}.tabs{-webkit-overflow-scrolling:touch;scrollbar-width:none}.tabs::-webkit-scrollbar{display:none}.pulse{min-width:0}.chip{white-space:nowrap}.kpi{min-width:0}.kpi b{overflow-wrap:anywhere}.calendar-head>div:first-child{min-width:0}.calendar-head h3,.event-title,.event-meta,.source{overflow-wrap:anywhere;word-break:keep-all}
.obsRange{align-items:center;margin:8px 0 2px;overflow-x:auto;flex-wrap:nowrap;padding-bottom:5px;-webkit-overflow-scrolling:touch;scrollbar-width:none}.obsRange::-webkit-scrollbar{display:none}.obsRange button{white-space:nowrap;flex:0 0 auto;min-height:30px}.obsFullBtn{font-weight:900!important}.obsGesture{align-self:center;white-space:nowrap}.obsCoverage{display:block;margin:2px 0 5px;color:#8a99aa;font-size:9px;line-height:1.35}.obsEventMetrics{display:flex;gap:6px;flex-wrap:wrap;margin-top:6px;font-size:10px}.obsEventMetrics span{background:#f6f8fb;border:1px solid #e7ecf2;padding:5px 7px;border-radius:7px;min-width:0}.obsEventMetrics b{margin-left:3px}.event{align-items:start}.obsNoScroll{overflow:hidden!important}.obsDone{color:#087443;font-weight:900}.obsPending{color:#718096}.obsMetricTable{margin-top:7px;border:1px solid #e7ecf2;border-radius:10px;overflow:hidden;width:100%;max-width:680px}.obsMetricRow{display:grid;grid-template-columns:minmax(120px,1.35fr) repeat(3,minmax(72px,.8fr));background:#fff;font-size:10px;border-top:1px solid #eef2f6}.obsMetricRow:first-child{border-top:0}.obsMetricRow>div{padding:6px 7px;border-left:1px solid #eef2f6;min-width:0;overflow-wrap:anywhere}.obsMetricRow>div:first-child{border-left:0}.obsMetricName{font-weight:900;color:#27364a}.obsMetricRow .forecast{background:#f4f7ff}.obsMetricRow .actual{background:#f1fbf5}.obsMetricRow b{margin-left:3px}
#obsFullChart{display:none;position:fixed;inset:0;z-index:9999;background:#f4f7fb;padding:10px;flex-direction:column}#obsFullChart.on{display:flex}.obsFullHead{display:flex;align-items:center;gap:8px;padding:5px 2px 10px;min-width:0}.obsFullHead b{flex:1;font-size:14px;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.obsFullHead button{border:1px solid #d8e0e9;background:#fff;border-radius:9px;padding:7px 10px;font-weight:850;flex:0 0 auto}.obsFullBody{flex:1;min-height:0;min-width:0;background:#fff;border:1px solid #e5ebf2;border-radius:14px;padding:8px}.obsFullBody canvas{width:100%!important;height:100%!important;max-width:100%!important}.obsFullHint{padding:7px 3px 1px;color:#718096;font-size:10px;text-align:center}
@media(min-width:761px) and (max-width:1100px){.wrap{padding:12px}.grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.card{padding:12px}.kpis{grid-template-columns:repeat(2,minmax(0,1fr))}.chart{height:330px!important}.event{grid-template-columns:78px 54px minmax(0,1fr) auto;gap:7px}.obsMetricRow{grid-template-columns:minmax(110px,1.2fr) repeat(3,minmax(66px,.8fr))}.tabs button{padding:8px 10px}}
@media(max-width:760px){.top{padding:12px 12px 10px}.brand{font-size:17px}.sub{font-size:10px}.pulse{gap:5px;margin-top:8px}.chip{font-size:9px;padding:5px 7px}.tabs{top:90px;padding:8px 10px;gap:5px}.tabs button{padding:8px 10px;font-size:11px}.wrap{padding:10px}.grid{grid-template-columns:1fr!important;gap:10px}.card{padding:11px;border-radius:14px}.card h3{font-size:14px}.kpis{grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}.kpi{padding:8px}.kpi b{font-size:13px}.chart{height:340px!important;margin-top:6px}.chart canvas{min-height:320px}.obsRange{margin:7px -1px 2px}.obsRange .obsGesture{display:none}.obsRange button{font-size:9px;padding:5px 7px}.obsCoverage{font-size:8px}.calendar-head{align-items:flex-start}.calendar-head>div:last-child{display:flex;gap:4px;flex:0 0 auto}.calendar-head button{padding:7px 9px}.event{grid-template-columns:minmax(0,1fr) auto!important;gap:5px 8px;padding:11px 0!important}.event .date{grid-column:1;font-size:11px}.event .country{grid-column:2;justify-self:end}.event .obsEventMain,.event>div:nth-child(3){grid-column:1/-1;min-width:0}.event .importance{grid-column:1/-1!important;display:flex;justify-content:space-between;align-items:center;gap:8px;white-space:normal}.event .source{display:block!important;text-align:right;max-width:75%;font-size:8px}.event-title{font-size:12px;line-height:1.35}.event-meta{font-size:9px}.obsMetricTable{max-width:none;border-radius:9px;overflow:hidden}.obsMetricRow{grid-template-columns:repeat(3,minmax(0,1fr));font-size:9px}.obsMetricName{grid-column:1/-1;background:#f8fafc;border-left:0!important;border-bottom:1px solid #eef2f6}.obsMetricRow>div{padding:6px 5px;white-space:normal}.obsPrev{border-left:0!important}.obsEventMetrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:4px}.obsEventMetrics span{text-align:center;padding:5px 3px}.foot{padding:16px 12px 28px}#obsFullChart{padding:max(8px,env(safe-area-inset-top)) 8px max(8px,env(safe-area-inset-bottom))}.obsFullBody{min-height:68vh}.obsFullHead button{padding:8px 9px;font-size:10px}.obsFullHead b{font-size:12px}}
@media(max-width:430px){.chart{height:360px!important}.obsFullBody{min-height:72vh}.kpis{grid-template-columns:repeat(2,minmax(0,1fr))}.calendar-head h3{font-size:13px}.calendar-head .meta{font-size:9px}}
@media(max-width:350px){.kpis{grid-template-columns:1fr}.tabs button{padding:7px 8px}.obsMetricRow{grid-template-columns:1fr}.obsMetricName,.obsPrev,.obsMetricRow .forecast,.obsMetricRow .actual{grid-column:1}.obsMetricRow>div{border-left:0!important;border-top:1px solid #eef2f6}.obsMetricName{border-top:0}}
@media(orientation:landscape) and (max-height:600px){#obsFullChart{padding:6px}.obsFullHead{padding-bottom:5px}.obsFullHint{display:none}.obsFullBody{min-height:0}}
`;document.head.appendChild(style);
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeFullscreen()});
window.addEventListener('load',()=>{try{globalThis.common=fullCommon}catch(_){};document.querySelectorAll('canvas').forEach(c=>ensureToolbar(c.id));try{if(typeof renderCalendar==='function')renderCalendar()}catch(_){};setTimeout(hydrateHistory,150)});
window.__JJOONI_OBSERVATORY_UI={version:'2.4-responsive-history',responsive:true,history_common:'FULL_NO_260_SLICE',ranges:RANGE_ORDER};
})();
